name: Update Firebase Lichsan

on:
  schedule:
    - cron: '14 4 * * *'  # Mỗi ngày vào lúc 04:14 UTC (chú ý múi giờ)
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  update-firebase:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install dependencies
        run: |
          npm install firebase-admin
          
      - name: Set up Firebase credentials
        run: |
          # Tạo file firebase-config.json ở thư mục gốc, 
          # để scripts/update-lichsan.js có thể require('../firebase-config.json')
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" > firebase-config.json
          
      - name: Update Date in Firestore
        run: |
          node ./scripts/update-lichsan.js
        env:
          GOOGLE_APPLICATION_CREDENTIALS: firebase-config.json
